setGeneric ( "geneNames" , function (object){ standardGeneric ( "geneNames" )})
setGeneric ( "selectContrib" , function ( object, cutoff, level, ...){ standardGeneric ( "selectContrib" )})
setGeneric ( "nbComp" , function ( object){ standardGeneric ( "nbComp" )})
setGeneric ( "getComp" , function ( object, level, ind){ standardGeneric ( "getComp" )})
setGeneric ( "getAssayData" , function ( object ){ standardGeneric ( "getAssayData" )})
setGeneric ( "datByGene<-" , function ( object, value){ standardGeneric ( "datByGene<-" )})
setGeneric ( "datByGene" , function ( object){ standardGeneric ( "datByGene" )})
setGeneric ( "getFeatureData" , function ( object ){ standardGeneric ( "getFeatureData" )})
setGeneric ( "getPhenoData" , function ( object ){ standardGeneric ( "getPhenoData" )})
setGeneric ( "getfData" , function ( object ){ standardGeneric ( "getfData" )})
setGeneric ( "S" , function ( object ){ standardGeneric ( "S" )})
setGeneric ( "getS" , function ( object ){ standardGeneric ( "getS" )})
setGeneric ( "S<-" , function ( object, value){ standardGeneric ( "S<-" )})
setGeneric ( "A" , function ( object ){ standardGeneric ( "A" )})
setGeneric ( "dat" , function ( object ){ standardGeneric ( "dat" )})
setGeneric ( "getA" , function ( object ){ standardGeneric ( "getA" )})
setGeneric ( "A<-" , function ( object, value){ standardGeneric ( "A<-" )})
setGeneric ( "dat<-" , function ( object, value){ standardGeneric ( "dat<-" )})
setGeneric ( "Slist" , function ( object ){ standardGeneric ( "Slist" )})
setGeneric ( "Alist" , function ( object ){ standardGeneric ( "Alist" )})
setGeneric ( "SlistByGene" , function ( object){ standardGeneric ( "SlistByGene" )})
setGeneric ( "getSByGene" , function ( object ){ standardGeneric ( "getSByGene" )})
setGeneric ( "SByGene" , function ( object ){ standardGeneric ( "SByGene" )})
setGeneric ( "SByGene<-" , function ( object, value){ standardGeneric ( "SByGene<-" )})
setGeneric ( "getLabelsComp" , function ( object ){ standardGeneric ( "getLabelsComp" )})
setGeneric ( "compNames" , function ( object ){ standardGeneric ( "compNames" )})
setGeneric ( "compNames<-" , function ( object, value){ standardGeneric ( "compNames<-" )})
setGeneric ( "sampleNames<-" , function ( object, value){ standardGeneric ( "sampleNames<-" )})
setGeneric ( "getIndComp" , function ( object ){ standardGeneric ( "getIndComp" )})
setGeneric ( "indComp" , function ( object ){ standardGeneric ( "indComp" )})
setGeneric ( "indComp<-" , function ( object, value){ standardGeneric ( "indComp<-" )})
setGeneric ( "witGenes" , function ( object ){ standardGeneric ( "witGenes" )})
setGeneric ( "witGenes<-" , function ( object, value ){ standardGeneric ( "witGenes<-" )})
setGeneric ( "getWitGenes" , function ( object ){ standardGeneric ( "getWitGenes" )})
setGeneric ( "getWitData" , function ( object ){ standardGeneric ( "getWitData" )})
setGeneric ( "getPackage" , function ( object ){ standardGeneric ( "getPackage" )})
setGeneric ( "getAnnotation" , function ( object ){ standardGeneric ( "getAnnotation" )})
setGeneric ( "package" , function ( object ){ standardGeneric ( "package" )})
setGeneric ( "chipVersion" , function ( object ){ standardGeneric ( "chipVersion" )})
setGeneric ( "getChipVersion" , function ( object ){ standardGeneric ( "getChipVersion" )})
setGeneric ( "chipVersion<-" , function ( object, value ){ standardGeneric ( "chipVersion<-" )})
setGeneric ( "getChipManu" , function ( object ){ standardGeneric ( "getChipManu" )})
setGeneric ( "chipManu" , function ( object ){ standardGeneric ( "chipManu" )})
setGeneric ( "chipManu<-" , function ( object, value ){ standardGeneric ( "chipManu<-" )})
setGeneric ( "getTypeID" , function ( object ){ standardGeneric ( "getTypeID" )})
setGeneric ( "typeID<-" , function ( object, value){ standardGeneric ( "typeID<-" )})
setGeneric ( "typeID" , function ( object ){ standardGeneric ( "typeID" )})
setGeneric ( "getMart" , function ( object ){ standardGeneric ( "getMart" )})
setGeneric ( "mart<-" , function ( object, value){ standardGeneric ( "mart<-" )})
setGeneric ( "mart" , function ( object ){ standardGeneric ( "mart" )})

# set
setGeneric ( "setFeatureData<-" , function ( object, value ){ standardGeneric ( "setFeatureData<-" )})
setGeneric ( "setfData<-" , function ( object, value ){ standardGeneric ( "setfData<-" )})
setGeneric ( "setPhenoData<-" , function ( object, value ){ standardGeneric ( "setPhenoData<-" )})
setGeneric ( "setAssayData<-" , function ( object, value ){ standardGeneric ( "setAssayData<-" )})
setGeneric ( "setAssayDataByGene<-" , function ( object,  value){ standardGeneric ( "setAssayDataByGene<-" )})
setGeneric ( "setA<-" , function ( object, value){ standardGeneric ( "setA<-" )})
setGeneric ( "setS<-" , function ( object, value){ standardGeneric ( "setS<-" )})
setGeneric ( "setSByGene<-" , function ( object, value){ standardGeneric ( "setSByGene<-" )})
setGeneric ( "setLabelsComp<-" , function ( object, value ){ standardGeneric ( "setLabelsComp<-" )})
setGeneric ( "setIndComp<-" , function ( object, value ){ standardGeneric ( "setIndComp<-" )})
setGeneric ( "setWitGenes<-" , function ( object, value ){ standardGeneric ( "setWitGenes<-" )})
setGeneric ( "setWitData<-" , function ( object, value ){ standardGeneric ( "setWitData<-" )})
setGeneric ( "setChipVersion<-" , function ( object, value ){ standardGeneric ( "setChipVersion<-" )})
setGeneric ( "setChipManu<-" , function ( object, value ){ standardGeneric ( "setChipManu<-" )})
setGeneric ( "setAnnotation<-" , function ( object, value ){ standardGeneric ( "setAnnotation<-" )})
setGeneric ( "setPackage<-" , function ( object, value ){ standardGeneric ( "setPackage<-" )})
setGeneric ( "package<-" , function ( object, value ){ standardGeneric ( "package<-" )})
setGeneric ( "setTypeID<-" , function ( object, value ){ standardGeneric ( "setTypeID<-" )})
setGeneric ( "typeID<-" , function ( object, value ){ standardGeneric ( "typeID<-" )})
setGeneric ( "setMart<-" , function ( object, value ){ standardGeneric ( "setMart<-" )})
setGeneric ( "mart<-" , function ( object, value ){ standardGeneric ( "mart<-" )})
                         
setGeneric ( "Afile" , function ( object){ standardGeneric ( "Afile" )})
setGeneric ( "Sfile" , function ( object){ standardGeneric ( "Sfile" )})
setGeneric ( "datfile" , function ( object){ standardGeneric ( "datfile" )})
setGeneric ( "annotfile" , function ( object){ standardGeneric ( "annotfile" )})
setGeneric ( "resPath" , function ( object){ standardGeneric ( "resPath" )})
setGeneric ( "genesPath" , function ( object){ standardGeneric ( "genesPath" )})
setGeneric ( "namesAnnot" , function ( object){ standardGeneric ( "namesAnnot" )})
setGeneric ( "annot2col" , function ( object){ standardGeneric ( "annot2col" )})
setGeneric ( "pvalCutoff" , function ( object){ standardGeneric ( "pvalCutoff" )})
setGeneric ( "selCutoff" , function ( object){ standardGeneric ( "selCutoff" )})
setGeneric ( "refSamples" , function ( object){ standardGeneric ( "refSamples" )})

setGeneric ( "getAfile" , function ( object){ standardGeneric ( "getAfile" )})
setGeneric ( "getSfile" , function ( object){ standardGeneric ( "getSfile" )})
setGeneric ( "getDatfile" , function ( object){ standardGeneric ( "getDatfile" )})
setGeneric ( "getAnnotfile" , function ( object){ standardGeneric ( "getAnnotfile" )})
setGeneric ( "getResPath" , function ( object){ standardGeneric ( "getResPath" )})
setGeneric ( "getGenesPath" , function ( object){ standardGeneric ( "getGenesPath" )})
setGeneric ( "getNamesAnnot" , function ( object){ standardGeneric ( "getNamesAnnot" )})
setGeneric ( "getAnnot2col" , function ( object){ standardGeneric ( "getAnnot2col" )})
setGeneric ( "getPvalCutoff" , function ( object){ standardGeneric ( "getPvalCutoff" )})
setGeneric ( "getSelCutoff" , function ( object){ standardGeneric ( "getSelCutoff" )})
setGeneric ( "getRefSamples" , function ( object){ standardGeneric ( "getRefSamples" )})


setGeneric ( "Afile<-" , function ( object, value ){ standardGeneric ( "Afile<-" )})
setGeneric ( "Sfile<-" , function ( object, value ){ standardGeneric ( "Sfile<-" )})
setGeneric ( "datfile<-" , function ( object, value ){ standardGeneric ( "datfile<-" )})
setGeneric ( "annotfile<-" , function ( object, value ){ standardGeneric ( "annotfile<-" )})
setGeneric ( "namesAnnot<-" , function ( object, value ){ standardGeneric ( "namesAnnot<-" )})
setGeneric ( "resPath<-" , function ( object, value ){ standardGeneric ( "resPath<-" )})
setGeneric ( "genesPath<-" , function ( object, value ){ standardGeneric ( "genesPath<-" )})
setGeneric ( "annot2col<-" , function ( object, value ){ standardGeneric ( "annot2col<-" )})
setGeneric ( "pvalCutoff<-" , function ( object, value ){ standardGeneric ( "pvalCutoff<-" )})
setGeneric ( "selCutoff<-" , function ( object, value ){ standardGeneric ( "selCutoff<-" )})
setGeneric ( "plotHist<-" , function ( object, value ){ standardGeneric ( "plotHist<-" )})
setGeneric ( "plotHeatmap<-" , function ( object, value ){ standardGeneric ( "plotHeatmap<-" )})
setGeneric ( "refSamples<-" , function ( object, value ){ standardGeneric ( "refSamples<-" )})

setGeneric ( "setAfile<-" , function ( object, value ){ standardGeneric ( "setAfile<-" )})
setGeneric ( "setSfile<-" , function ( object, value ){ standardGeneric ( "setSfile<-" )})
setGeneric ( "setAnnotfile<-" , function ( object, value ){ standardGeneric ( "setAnnotfile<-" )})
setGeneric ( "setDatfile<-" , function ( object, value ){ standardGeneric ( "setDatfile<-" )})
setGeneric ( "setResPath<-" , function ( object, value ){ standardGeneric ( "setResPath<-" )})
setGeneric ( "setGenesPath<-" , function ( object, value ){ standardGeneric ( "setGenesPath<-" )})
setGeneric ( "setNamesAnnot<-" , function ( object, value ){ standardGeneric ( "setNamesAnnot<-" )})
setGeneric ( "setAnnot2col<-" , function ( object, value ){ standardGeneric ( "setAnnot2col<-" )})
setGeneric ( "setPvalCutoff<-" , function ( object, value ){ standardGeneric ( "setPvalCutoff<-" )})
setGeneric ( "setSelCutoff<-" , function ( object, value ){ standardGeneric ( "setSelCutoff<-" )})
setGeneric ( "setRefSamples<-" , function ( object, value ){ standardGeneric ( "setRefSamples<-" )})


